import { ROLES, ACCESS, PERMISSION_COLUMNS, SECURITY_NOTICE, allowedScopes, canAccess, canAssignRoles, isInScope, permissionStatus } from './role-permissions.js';
import { CONTEXT, metrics, employees, tickets, reports, alerts, auditEntries } from './mock-operations-data.js';

const state = { role: sessionStorage.getItem('ux-r01-role') || 'owner_super_admin', scope: sessionStorage.getItem('ux-r01-scope') || 'global', screen: 'overview', selectedEmployee: employees[0], selectedTicket: tickets[0] };
const app = document.querySelector('#app'), entry = document.querySelector('#entry-screen'), sidebar = document.querySelector('#sidebar'), main = document.querySelector('#main-content');
const labels = { overview:'نظرة عامة', users:'المستخدمون', employees:'الموظفون', listings:'الإعلانات', moderation:'البلاغات', 'tiger-care':'Tiger Care', sectors:'القطاعات', regions:'المناطق', sales:'المبيعات', marketing:'التسويق', providers:'مزودو الخدمات', reports:'التقارير', alerts:'التنبيهات', audit:'سجل التدقيق', matrix:'مصفوفة الصلاحيات', settings:'الإعدادات' };
const icons = { overview:'◈', users:'◉', employees:'◫', listings:'▤', moderation:'⚑', 'tiger-care':'✦', sectors:'▧', regions:'⌖', sales:'↗', marketing:'◎', providers:'◇', reports:'▥', alerts:'♢', audit:'◌', matrix:'▦', settings:'⚙' };

function roleInfo() { return ROLES.find((item) => item.id === state.role); }
function context() { return { ...CONTEXT, scope: state.scope }; }
function normalizeScope() { if (!allowedScopes(state.role).includes(state.scope)) state.scope = roleInfo().defaultScope; }
function save() { normalizeScope(); sessionStorage.setItem('ux-r01-role', state.role); sessionStorage.setItem('ux-r01-scope', state.scope); }
function escape(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]); }
function badge(value) { const c = value === 'عاجلة' || value === 'حرج' ? 'urgent' : value === 'عالية' || value === 'عالي' ? 'high' : value === 'متوسطة' || value === 'متوسط' ? 'medium' : 'low'; return `<span class="badge ${c}">${escape(value)}</span>`; }
function toast(message, error = false) { const node = document.createElement('div'); node.className = `toast${error ? ' error' : ''}`; node.textContent = message; document.querySelector('#toast-root').append(node); setTimeout(() => node.remove(), 3200); }
function accessible(items) { return items.filter((item) => isInScope(item, context())); }

document.addEventListener('change', (event) => {
	if (event.target.id !== 'preview-role') return;
	const scopeSelect = document.querySelector('#preview-scope');
	scopeSelect.innerHTML = allowedScopes(event.target.value).map((scope) => `<option>${scope}</option>`).join('');
});

document.addEventListener('click', (event) => {
	if (event.target.id !== 'assignment-review') return;
	const form = document.querySelector('#assignment-form');
	if (!form) return;
	const values = Object.fromEntries(new FormData(form));
	const selectedEmployee = employees.find((item) => item.id === values.user);
	const invalidScope = !allowedScopes(state.role).includes(values.scope);
	if (selectedEmployee?.name !== CONTEXT.actor && !invalidScope) return;
	event.preventDefault();
	event.stopImmediatePropagation();
	const error = document.querySelector('#assignment-error');
	error.hidden = false;
	error.textContent = selectedEmployee?.name === CONTEXT.actor
		? 'لا يمكن للمستخدم تعيين نفسه في المعاينة.'
		: 'لا يمكن تجاوز Scope الشخص المخول في المعاينة.';
}, true);

function renderEntry() { const role = roleInfo(); const denied = state.role === 'regular_user'; entry.hidden = false; app.hidden = true; entry.innerHTML = `<div class="entry-card"><div class="brand">VVIP TIGER</div><h1 id="entry-title">مركز العمليات</h1><p>معاينة واجهة تشغيلية محلية، مصممة لمراجعة الأدوار والنطاقات دون تسجيل دخول جديد أو استبدال Clerk.</p><div class="notice">${SECURITY_NOTICE}</div><div class="context-grid"><div><span>المستخدم التجريبي</span><strong>${CONTEXT.actor}</strong></div><div><span>الدور الحالي</span><strong>${role.label}</strong></div><div><span>النطاق الحالي</span><strong>${state.scope}</strong></div></div>${denied ? `<div class="notice">تم رفض الدخول: الحساب التجريبي العادي لا يملك صلاحية لمركز العمليات.</div>` : ''}<button class="primary" id="enter-console" ${denied ? 'disabled' : ''}>دخول مركز العمليات</button><button class="secondary" id="entry-role" style="margin-inline-start:8px">تغيير دور المعاينة</button></div>`; document.querySelector('#enter-console')?.addEventListener('click', enterConsole); document.querySelector('#entry-role').addEventListener('click', openRoleSelector); }
function enterConsole() { entry.hidden = true; app.hidden = false; renderApp(); }
function renderApp() { renderSidebar(); renderScreen(); }
function renderSidebar() { const role = roleInfo(); sidebar.innerHTML = `<div class="brand">VVIP TIGER<br><small>مركز العمليات</small></div><div class="sidebar-context"><strong>${role.label}</strong><span>${state.scope} · ${CONTEXT.actor}</span></div><nav class="nav-list">${ACCESS[state.role].map((item) => `<button class="nav-button ${state.screen === item ? 'active' : ''}" data-screen="${item}"><span>${icons[item]}</span>${labels[item]}</button>`).join('')}</nav><p class="sidebar-context">Preview محلي فقط<br>لا توجد صلاحيات إنتاجية.</p>`; sidebar.querySelectorAll('[data-screen]').forEach((button) => button.addEventListener('click', () => navigate(button.dataset.screen))); }
function navigate(screen) { state.screen = screen; sidebar.classList.remove('open'); document.querySelector('#menu-button').setAttribute('aria-expanded','false'); renderApp(); }
function denied(screen = state.screen) { document.querySelector('#page-title').textContent = 'منع الوصول'; main.innerHTML = `<section class="access-denied"><p class="eyebrow">LOCAL PREVIEW</p><h2>لا يمكن فتح هذه الشاشة</h2><p>الدور <strong>${roleInfo().label}</strong> لا يملك الوصول إلى «${labels[screen] || screen}» ضمن النطاق الحالي.</p><div class="access-codes"><div><strong>Access Denied</strong><br>تم رفض الوصول.</div><div><strong>Role Missing</strong><br>الدور لا يتضمن هذه الميزة.</div><div><strong>Scope Missing</strong><br>لا يوجد نطاق مناسب للبيانات.</div><div><strong>Higher Approval Required</strong><br>هذه العملية تحتاج موافقة أعلى.</div><div><strong>Permission Expired</strong><br>مثال لحالة انتهاء الصلاحية.</div><div><strong>Production Security Not Ready</strong><br>المعاينة ليست إنتاجًا.</div></div><button class="primary" id="back-overview">العودة للنظرة العامة</button></section>`; document.querySelector('#back-overview').addEventListener('click', () => navigate('overview')); }
function shell(title, subtitle, body, action = '') { document.querySelector('#page-title').textContent = title; main.innerHTML = `<section class="screen-head"><div><p class="eyebrow">${roleInfo().label} · ${state.scope}</p><h2>${title}</h2><p>${subtitle}</p></div>${action}</section>${body}`; }
function overview() { const filteredMetrics = state.role === 'owner_super_admin' || state.role === 'platform_admin' ? metrics : metrics.slice(0,4); shell('لوحة العمليات', 'ملخص تشغيلي محلي يراعي الدور والنطاق التجريبي.', `<section class="metric-grid">${filteredMetrics.map(([title,value,note])=>`<article class="metric-card"><span>${title}</span><strong>${value}</strong><small>${note}</small></article>`).join('')}</section><section class="layout-two"><article class="panel"><h3>اختصارات تشغيلية</h3><div class="quick-grid">${['employees','matrix','tiger-care','moderation','reports','audit'].filter((s)=>canAccess(state.role,s)).map((screen)=>`<button data-go="${screen}">${icons[screen]} ${labels[screen]}</button>`).join('') || '<p>لا توجد اختصارات متاحة لهذا الدور.</p>'}</div></article><article class="panel"><h3>تنبيهات تحتاج انتباهًا</h3><ul class="alert-list">${alerts.slice(0,4).map((a)=>`<li><button data-alert="${a.linked}"><span>${a.title}</span>${badge(a.level)}</button></li>`).join('')}</ul></article></section>`); main.querySelectorAll('[data-go]').forEach((button)=>button.addEventListener('click',()=>navigate(button.dataset.go))); main.querySelectorAll('[data-alert]').forEach((button)=>button.addEventListener('click',()=>openLinked(button.dataset.alert))); }
function tableScreen(type) { const config = { users:['المستخدمون','قائمة حسابات تجريبية ضمن نطاق الدور.', employees], listings:['الإعلانات','إعلانات تجريبية تنتظر المراجعة حسب النطاق.', reports], providers:['مزودو الخدمات','طلبات انضمام ومراجعة محلية فقط.', employees] }[type]; const rows = accessible(config[2]); shell(config[0], config[1], `<div class="controls"><input id="table-search" placeholder="بحث محلي"><select id="status-filter"><option value="">كل الحالات</option><option>نشطة</option><option>مراجعة</option><option>قيد المراجعة</option></select></div><div id="table-content">${renderTable(type, rows)}</div>`); bindTableFilter(type, config[2]); }
function renderTable(type, rows) { if (!rows.length) return '<div class="empty">لا توجد بيانات ضمن Scope المعاينة الحالي.</div>'; if (type === 'employees' || type === 'users' || type === 'providers') return `<div class="table-wrap"><table><thead><tr><th>الاسم</th><th>الدور</th><th>النطاق</th><th>القطاع</th><th>المنطقة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows.map((e)=>`<tr><td data-label="الاسم">${e.name}</td><td data-label="الدور">${e.role}</td><td data-label="النطاق">${e.scope}</td><td data-label="القطاع">${e.sector}</td><td data-label="المنطقة">${e.region}</td><td data-label="الحالة">${badge(e.status)}</td><td data-label="إجراء"><button class="row-button" data-employee="${e.id}">فتح الملف</button></td></tr>`).join('')}</tbody></table></div>`; return `<div class="table-wrap"><table><thead><tr><th>المعرف</th><th>العنوان</th><th>الكيان</th><th>الأولوية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows.map((r)=>`<tr><td data-label="المعرف">${r.id}</td><td data-label="العنوان">${r.title}</td><td data-label="الكيان">${r.entity || r.sector}</td><td data-label="الأولوية">${badge(r.priority)}</td><td data-label="الحالة">${r.status}</td><td data-label="إجراء"><button class="row-button" data-report="${r.id}">فتح المراجعة</button></td></tr>`).join('')}</tbody></table></div>`; }
function bindTableFilter(type, items) { const refresh = () => { const term = document.querySelector('#table-search').value.trim(); const status = document.querySelector('#status-filter').value; const rows = accessible(items).filter((i)=>JSON.stringify(i).includes(term) && (!status || i.status === status)); document.querySelector('#table-content').innerHTML = renderTable(type,rows); bindRowActions(); }; document.querySelector('#table-search').addEventListener('input',refresh); document.querySelector('#status-filter').addEventListener('change',refresh); bindRowActions(); }
function bindRowActions() { main.querySelectorAll('[data-employee]').forEach((button)=>button.addEventListener('click',()=>employeeProfile(employees.find((e)=>e.id===button.dataset.employee)))); main.querySelectorAll('[data-report]').forEach((button)=>reportDetail(reports.find((r)=>r.id===button.dataset.report)))); }
function employeeProfile(employee) { if (!employee || !canAccess(state.role,'employees')) return denied('employees'); state.selectedEmployee = employee; shell('الملف الداخلي للموظف', 'بيانات نموذجية بدون كلمات مرور أو Tokens أو Secrets.', `<section class="layout-two"><article class="panel"><h3>${employee.name} · ${employee.id}</h3><div class="form-grid"><p><strong>الحساب العادي المرتبط:</strong><br>حساب تجريبي محلي</p><p><strong>الوظيفة:</strong><br>${employee.role}</p><p><strong>Scope:</strong><br>${employee.scope}</p><p><strong>القطاع:</strong><br>${employee.sector}</p><p><strong>المنطقة:</strong><br>${employee.region} / ${employee.area}</p><p><strong>المدير المباشر:</strong><br>مدير تجريبي</p><p><strong>بدء الصلاحية:</strong><br>${employee.assigned}</p><p><strong>الحالة:</strong><br>${badge(employee.status)}</p></div></article><article class="panel"><h3>خيارات الملف</h3>${canAssignRoles(state.role) ? `<button id="assign-from-profile" class="primary">تعيين دور</button><button class="secondary" data-confirm="تعديل النطاق">تعديل النطاق</button><button class="danger" data-confirm="تعليق الصلاحية">تعليق الصلاحية</button>` : '<p class="notice">خيارات تعديل الصلاحيات محجوبة لهذا الدور.</p>'}<button class="secondary" id="employee-audit">عرض سجل التدقيق</button></article></section><section class="layout-two"><article class="panel"><h3>سجل تغييرات الدور</h3><ul class="timeline"><li>تمت مراجعة الصلاحية — 2026-07-12</li><li>تم تعيين Scope الحالي — 2026-06-01</li></ul></article><article class="panel"><h3>تنبيهات الأمان</h3><ul class="timeline"><li>لا توجد بيانات مصادقة في المعاينة.</li><li>مراجعة انتهاء الصلاحية قبل التمديد.</li></ul></article></section>`); document.querySelector('#assign-from-profile')?.addEventListener('click',()=>assignmentDrawer(employee)); document.querySelector('#employee-audit').addEventListener('click',()=>navigate('audit')); main.querySelectorAll('[data-confirm]').forEach((button)=>button.addEventListener('click',()=>confirmation(button.dataset.confirm))); }
function tigerCare() { const rows=accessible(tickets); shell('Tiger Care', 'صندوق تذاكر تجريبي، غير متصل بمستخدمين أو رسائل حقيقية.', `<div class="controls"><select id="ticket-status"><option value="">كل الحالات</option>${[...new Set(tickets.map((t)=>t.status))].map((s)=>`<option>${s}</option>`).join('')}</select><select id="ticket-priority"><option value="">كل الأولويات</option><option>عاجلة</option><option>عالية</option><option>متوسطة</option></select><input id="ticket-search" placeholder="بحث في التذاكر"></div><div id="ticket-content" class="ticket-grid">${ticketCards(rows)}</div>`); const refresh=()=>{const status=document.querySelector('#ticket-status').value,priority=document.querySelector('#ticket-priority').value,term=document.querySelector('#ticket-search').value; document.querySelector('#ticket-content').innerHTML=ticketCards(rows.filter((t)=>(!status||t.status===status)&&(!priority||t.priority===priority)&&JSON.stringify(t).includes(term))); bindTicketCards();}; ['ticket-status','ticket-priority'].forEach((id)=>document.querySelector(`#${id}`).addEventListener('change',refresh)); document.querySelector('#ticket-search').addEventListener('input',refresh); bindTicketCards(); }
function ticketCards(rows) { return rows.length ? rows.map((t)=>`<article class="data-card"><h3>${t.id} · ${t.title}</h3><p>${t.message}</p><div class="card-meta">${badge(t.priority)}<span class="badge medium">${t.status}</span><span class="badge low">${t.sector}</span></div><small>${t.updated} · ${t.assignee}</small><div class="card-actions"><button class="secondary" data-ticket="${t.id}">فتح التذكرة</button><button class="primary" data-status="${t.id}">تحديث الحالة</button></div></article>`).join('') : '<div class="empty">لا توجد تذاكر في النطاق الحالي.</div>'; }
function bindTicketCards() { main.querySelectorAll('[data-ticket]').forEach((button)=>button.addEventListener('click',()=>ticketDetail(tickets.find((t)=>t.id===button.dataset.ticket)))); main.querySelectorAll('[data-status]').forEach((button)=>button.addEventListener('click',()=>changeTicketStatus(tickets.find((t)=>t.id===button.dataset.status)))); }
function ticketDetail(ticket) { state.selectedTicket=ticket; shell('بطاقة Tiger Care', 'محتوى تجريبي؛ ردود المعاينة لا ترسل أي رسالة.', `<section class="layout-two"><article class="panel"><h3>${ticket.id} · ${ticket.title}</h3><p><strong>رسالة المستخدم التجريبية:</strong> ${ticket.message}</p><p class="notice">تم استلام طلبك، وسيتم التواصل معك خلال 24 ساعة.</p><h3>Timeline</h3><ul class="timeline">${ticket.timeline.map((event)=>`<li>${event}</li>`).join('')}</ul></article><article class="panel"><h3>إجراءات محلية</h3><label>ملاحظة داخلية<textarea placeholder="لن تحفظ خارج جلسة المعاينة"></textarea></label><div class="card-actions"><button class="primary" data-status-action>Change Status</button><button class="secondary" data-confirm="Assign">Assign</button><button class="secondary" data-confirm="Escalate">Escalate</button><button class="secondary" data-confirm="Reply Preview">Reply Preview</button></div></article></section>`); document.querySelector('[data-status-action]').addEventListener('click',()=>changeTicketStatus(ticket)); main.querySelectorAll('[data-confirm]').forEach((button)=>button.addEventListener('click',()=>confirmation(button.dataset.confirm))); }
function changeTicketStatus(ticket) { ticket.status = ticket.status === 'قيد المراجعة' ? 'بانتظار المستخدم' : 'قيد المراجعة'; toast(`تم تحديث حالة ${ticket.id} في المعاينة فقط.`); tigerCare(); }
function moderation() { const rows=accessible(reports); shell('الإشراف والبلاغات','لا تظهر هوية المبلّغ دون صلاحية، والأدلة تجريبية فقط.',`<div class="ticket-grid">${rows.map((r)=>`<article class="data-card"><h3>${r.id} · ${r.title}</h3><p>الكيان: ${r.entity}<br>الأدلة: ${r.evidence}</p><div class="card-meta">${badge(r.priority)}<span class="badge medium">${r.status}</span></div><div class="card-actions"><button class="secondary" data-report="${r.id}">فتح البلاغ</button><button class="danger" data-sensitive="إزالة المحتوى Preview">إزالة Preview</button></div></article>`).join('') || '<div class="empty">لا توجد بلاغات في النطاق الحالي.</div>'}</div>`); main.querySelectorAll('[data-report]').forEach((button)=>button.addEventListener('click',()=>reportDetail(reports.find((r)=>r.id===button.dataset.report)))); main.querySelectorAll('[data-sensitive]').forEach((button)=>button.addEventListener('click',()=>confirmation(button.dataset.sensitive))); }
function reportDetail(report) { shell('مراجعة البلاغ', 'كل الإجراءات التالية محاكاة محلية وتتطلب تأكيدًا.', `<section class="layout-two"><article class="panel"><h3>${report.id} · ${report.title}</h3><p><strong>الكيان المرتبط:</strong> ${report.entity}</p><p><strong>نوع المخالفة:</strong> ${report.title}</p><p><strong>الأدلة التجريبية:</strong> ${report.evidence}</p><p class="notice">بيانات المُبلّغ محجوبة في المعاينة.</p></article><article class="panel"><h3>قرار المراجعة</h3><div class="card-actions"><button class="secondary" data-confirm="رفض البلاغ">رفض البلاغ</button><button class="secondary" data-confirm="طلب معلومات إضافية">طلب معلومات إضافية</button><button class="danger" data-confirm="إزالة المحتوى Preview">إزالة المحتوى Preview</button><button class="danger" data-confirm="تعليق الحساب Preview">تعليق الحساب Preview</button><button class="secondary" data-confirm="إحالة للإدارة">إحالة للإدارة</button></div></article></section>`); main.querySelectorAll('[data-confirm]').forEach((button)=>button.addEventListener('click',()=>confirmation(button.dataset.confirm))); }
function geographic() { const title=state.screen==='sectors'?'القطاعات':'المناطق'; shell(title, 'عرض نطاق نصي محلي، وليس خريطة GPS أو خدمة مدفوعة.', `<section class="section-stack"><div class="map-band"><strong>النطاق الحالي:</strong> ${state.scope} — ${CONTEXT.sector} / ${CONTEXT.region} / ${CONTEXT.area}</div><section class="metric-grid"><article class="metric-card"><span>إعلانات النطاق</span><strong>37</strong><small>محلية للمعاينة</small></article><article class="metric-card"><span>شكاوى مفتوحة</span><strong>6</strong><small>ضمن النطاق</small></article><article class="metric-card"><span>موظفون مسندون</span><strong>4</strong><small>بدون بيانات حقيقية</small></article></section><article class="panel"><h3>التصعيد ومقارنة الأداء التشغيلي</h3><p>يعرض هذا النموذج أولوية الحالات وتوزيعها داخل النطاق فقط، دون موقع GPS أو أي بيانات إنتاج.</p></article></section>`); }
function future(type) { const titles={sales:'المبيعات',marketing:'التسويق والحملات',providers:'مزودو الخدمات',reports:'التقارير التشغيلية',settings:'الإعدادات'}; const content=type==='providers'?renderTable('providers',accessible(employees)):`<section class="layout-two"><article class="panel"><h3>المتابعات والمهام</h3><p>عملاء ومتاجر وشركات ومهام فريق تجريبية، مع ملاحظات داخلية غير محفوظة.</p><div class="quick-grid"><button>متابعة جديدة</button><button>قائمة مهام</button><button>طلب مراجعة</button></div></article><article class="panel"><h3>مؤشرات تشغيلية</h3><p>لا توجد فواتير أو مدفوعات أو عمولات أو بطاقات بنكية.</p><p class="future">ميزة تشغيلية مستقبلية — غير متصلة بالإنتاج</p></article></section>`; shell(titles[type], 'واجهة تشغيلية مستقبلية ببيانات محلية فقط.', `<p class="future">ميزة تشغيلية مستقبلية — غير متصلة بالإنتاج</p>${content}`); }
function audit() { const rows=state.role==='sales_agent'?auditEntries.filter((e)=>e.actor===CONTEXT.actor):auditEntries; shell('سجل التدقيق','أحداث Mock بلا IP أو بيانات أجهزة حقيقية.',`<div class="controls"><input id="audit-search" placeholder="بحث محلي في السجل"><button class="secondary" disabled>Export Preview غير فعال</button></div><div id="audit-content">${auditTable(rows)}</div>`); document.querySelector('#audit-search').addEventListener('input',(event)=>document.querySelector('#audit-content').innerHTML=auditTable(rows.filter((row)=>JSON.stringify(row).includes(event.target.value)))); }
function auditTable(rows) { return `<div class="table-wrap"><table><thead><tr><th>الفاعل</th><th>الدور</th><th>الإجراء</th><th>الكيان</th><th>السبب</th><th>الوقت</th><th>Scope</th><th>النتيجة</th><th>الخطورة</th></tr></thead><tbody>${rows.map((r)=>`<tr>${[['الفاعل',r.actor],['الدور',r.role],['الإجراء',r.action],['الكيان',r.entity],['السبب',r.reason],['الوقت',r.time],['Scope',r.scope],['النتيجة',r.result],['الخطورة',r.risk]].map(([label,value])=>`<td data-label="${label}">${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`; }
function matrix() { const role=roleInfo(); shell('مصفوفة الصلاحيات','تتغير المصفوفة بصريًا عند تغيير دور المعاينة.',`<p class="notice">الدور المعروض: <strong>${role.label}</strong> · Scope: <strong>${state.scope}</strong></p><div class="table-wrap matrix"><table><thead><tr><th>الدور</th>${PERMISSION_COLUMNS.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody><tr><td>${role.label}</td>${PERMISSION_COLUMNS.map(([id])=>{const value=permissionStatus(state.role,id);return `<td class="status-${value.replaceAll(' ','-')}">${value}</td>`;}).join('')}</tr></tbody></table></div>`); }
function alertsScreen() { shell('التنبيهات والتصعيد','تنبيهات تجريبية محلية فقط.',`<section class="section-stack">${alerts.map((a,index)=>`<article class="panel"><h3>${a.title} ${badge(a.level)}</h3><p>العنصر المرتبط: ${a.linked}</p><button class="secondary" data-mark="${index}">Mark as Read</button><button class="primary" data-open="${a.linked}">فتح العنصر المرتبط</button></article>`).join('')}</section>`); main.querySelectorAll('[data-mark]').forEach((button)=>button.addEventListener('click',()=>{alerts[button.dataset.mark].read=true;toast('تم تعليم التنبيه كمقروء في هذه الجلسة.');})); main.querySelectorAll('[data-open]').forEach((button)=>button.addEventListener('click',()=>openLinked(button.dataset.open))); }
function openLinked(id) { if(id.startsWith('TC')) { if(canAccess(state.role,'tiger-care')) ticketDetail(tickets.find((t)=>t.id===id)); else denied('tiger-care'); } else if(id.startsWith('R-')) { if(canAccess(state.role,'moderation')) reportDetail(reports.find((r)=>r.id===id)); else denied('moderation'); } else if(id.startsWith('EMP')) employeeProfile(employees.find((e)=>e.id===id)); else if(canAccess(state.role,'audit')) navigate('audit'); else denied('audit'); }
function assignmentDrawer(employee=state.selectedEmployee) { if(!canAssignRoles(state.role)) return denied('employees'); modal('تعيين دور وصلاحيات', `<p class="notice">محاكاة Frontend فقط. لا يمكن منح Owner ولا يمكن للمستخدم تعيين نفسه.</p><form id="assignment-form" class="form-grid"><label>1. المستخدم<select name="user" required><option value="${employee.id}">${employee.name}</option>${employees.filter((e)=>e.id!==employee.id).map((e)=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></label><label>2. الدور<select name="role" required>${ROLES.filter((r)=>r.id!=='owner_super_admin').map((r)=>`<option value="${r.id}">${r.label}</option>`).join('')}</select></label><label>3. Scope<select name="scope" required>${SCOPES.map((s)=>`<option>${s}</option>`).join('')}</select></label><label>4. القطاع<select name="sector"><option>${CONTEXT.sector}</option><option>المواد والتوريدات</option><option>العقارات</option></select></label><label>5. المنطقة<select name="region"><option>${CONTEXT.region}</option><option>الزرقاء</option></select></label><label>6. تاريخ البداية<input name="start" type="date" required value="2026-07-16"></label><label>7. تاريخ الانتهاء<input name="end" type="date"></label><label style="grid-column:1/-1">8. سبب التعيين إلزامي<textarea name="reason" required placeholder="اشرح سبب التعيين"></textarea></label><p id="assignment-error" class="field-error" hidden></p></form>`, `<button class="secondary" data-close>إلغاء</button><button class="primary" id="assignment-review">9. مراجعة الملخص</button>`); document.querySelector('#assignment-review').addEventListener('click',()=>{const form=document.querySelector('#assignment-form');if(!form.reportValidity()) return;const data=Object.fromEntries(new FormData(form)); if(data.user===employees[0].id && state.role!== 'owner_super_admin'){document.querySelector('#assignment-error').hidden=false;document.querySelector('#assignment-error').textContent='لا يمكن للمستخدم تعيين نفسه في المعاينة.';return;} confirmation('تأكيد تعيين الدور',()=>{closeModal();toast(`نجح تعيين ${data.role} في Preview فقط. أضيف الحدث إلى Audit Log محليًا.`);auditEntries.unshift({actor:CONTEXT.actor,role:roleInfo().label,action:'تعيين دور Preview',entity:data.user,reason:data.reason,time:'2026-07-16 الآن',scope:data.scope,result:'Preview فقط',risk:'عالي'});});}); }
function openRoleSelector() { modal('اختيار دور المعاينة', `<p class="notice">تبديل محلي داخل sessionStorage فقط، وليس تسجيل دخول أو تصريحًا فعليًا.</p><div class="form-grid"><label>الدور<select id="preview-role">${ROLES.map((r)=>`<option value="${r.id}" ${r.id===state.role?'selected':''}>${r.label}</option>`).join('')}</select></label><label>Scope<select id="preview-scope">${SCOPES.map((scope)=>`<option ${scope===state.scope?'selected':''}>${scope}</option>`).join('')}</select></label></div>`, `<button class="secondary" data-close>إلغاء</button><button class="primary" id="apply-role">تطبيق المعاينة</button>`); document.querySelector('#apply-role').addEventListener('click',()=>{state.role=document.querySelector('#preview-role').value;state.scope=document.querySelector('#preview-scope').value;state.screen='overview';save();closeModal();renderEntry();toast('تم تغيير دور المعاينة محليًا.');}); }
function confirmation(action,onConfirm=()=>{toast(`${action} تم تأكيده في المعاينة فقط.`);closeModal();}) { modal('تأكيد الإجراء', `<p>هل تريد متابعة «${action}»؟ لن يتغير أي نظام إنتاجي أو بيانات حقيقية.</p>`, `<button class="secondary" data-close>إلغاء</button><button class="danger" id="confirm-action">تأكيد Preview</button>`); document.querySelector('#confirm-action').addEventListener('click',onConfirm); }
function modal(title,body,footer) { document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${title}</h2><button class="icon-button" data-close aria-label="إغلاق">×</button></header><div class="modal-body">${body}</div><footer class="modal-foot">${footer}</footer></section></div>`; document.querySelectorAll('[data-close]').forEach((button)=>button.addEventListener('click',closeModal)); document.querySelector('.modal [data-close]')?.focus(); }
function closeModal() { document.querySelector('#modal-root').innerHTML=''; }
function renderScreen() { if(!canAccess(state.role,state.screen)) return denied(); const renderers={overview,users:()=>tableScreen('users'),employees:()=>tableScreen('employees'),listings:()=>tableScreen('listings'),'tiger-care':tigerCare,moderation,regions:geographic,sectors:geographic,sales:()=>future('sales'),marketing:()=>future('marketing'),providers:()=>future('providers'),reports:()=>future('reports'),settings:()=>future('settings'),audit,matrix,alerts:alertsScreen}; (renderers[state.screen] || overview)(); }
document.querySelector('#role-button').addEventListener('click',openRoleSelector); document.querySelector('#alerts-button').addEventListener('click',()=>navigate('alerts')); document.querySelector('#menu-button').addEventListener('click',()=>{const open=sidebar.classList.toggle('open');document.querySelector('#menu-button').setAttribute('aria-expanded',String(open));}); normalizeScope(); renderEntry();