'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const{pathToFileURL}=require('node:url');
const url=pathToFileURL(path.resolve(__dirname,'../scripts/media/f05-media-passport.js')).href;
async function load(){return import(`${url}?x=${Date.now()}-${Math.random()}`);}
function candidate(overrides={}){return{outputMime:'image/webp',width:1600,height:1200,sizeBytes:250000,sha256:'a'.repeat(64),...overrides};}
function context(overrides={}){return{mediaPolicyVersion:'F05_BPLUS_V1',processorVersion:'pr36-f05-1',sourceClass:'heic',decodeRoute:'wasm',createdAt:'2026-08-14T10:00:00.000Z',...overrides};}
test('F05 passport has an exact bounded non-sensitive schema',async()=>{const{createMediaPassport}=await load();const p=createMediaPassport(candidate(),context());assert.deepEqual(Object.keys(p).sort(),['schemaVersion','mediaPolicyVersion','processorVersion','sourceClass','decodeRoute','outputMime','width','height','sizeBytes','sha256','metadataStripped','colorSpace','createdAt'].sort());assert.equal(p.schemaVersion,'F05_MEDIA_PASSPORT_V1');assert.equal(p.metadataStripped,true);assert.equal(p.colorSpace,'srgb');assert.equal(Object.isFrozen(p),true);for(const k of ['filename','path','gps','exif','deviceId','publicUrl','rawBytes'])assert.equal(k in p,false);});
test('F05 passport accepts only canonical JPEG/WebP 4:3 bounded candidates',async()=>{const{createMediaPassport}=await load();assert.equal(createMediaPassport(candidate({outputMime:'image/jpeg'}),context()).outputMime,'image/jpeg');for(const bad of [candidate({outputMime:'image/png'}),candidate({width:1601}),candidate({width:1000,height:1000}),candidate({sizeBytes:0}),candidate({sha256:'ABC'})])assert.throws(()=>createMediaPassport(bad,context()),/media_passport_invalid/);});
test('F05 passport rejects unknown source/decode policy and malformed timestamps',async()=>{const{createMediaPassport}=await load();for(const c of [context({sourceClass:'gif'}),context({decodeRoute:'server'}),context({mediaPolicyVersion:'F04'}),context({createdAt:'yesterday'})])assert.throws(()=>createMediaPassport(candidate(),c),/media_passport_invalid/);});
