'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const{pathToFileURL}=require('node:url');const url=pathToFileURL(path.resolve(__dirname,'../scripts/media/f05-heif-adapter.js')).href;async function load(){return import(`${url}?x=${Date.now()}-${Math.random()}`);}
const POLICY=Object.freeze({maxPixels:40000000,minWidth:320,minHeight:240,maxWidth:1600,maxHeight:1200,webpQuality:0.82,jpegQuality:0.86});
function job(){return{jobId:'job_1',bytes:new ArrayBuffer(16),mimeType:'image/heic',transform:Object.freeze({zoom:1,panX:0,panY:0}),policy:POLICY,signal:null};}function frame(){return{width:1600,height:1200,pixelsOrDisplayFrame:{kind:'test'},orientationApplied:true,colorSpace:'srgb',sourceKind:'heic'};}
test('F05 adapter chooses native only after explicit support probe',async()=>{const{createHeifAdapter}=await load();let wasm=0;const a=createHeifAdapter({nativeProbe:async()=>true,nativeDecode:async()=>frame(),wasmDecode:async()=>{wasm++;return frame();}});const r=await a.process(job());assert.equal(r.decodeRoute,'native');assert.equal(wasm,0);assert.equal(Object.isFrozen(r),true);});
test('F05 adapter uses WASM only when native support probe is false',async()=>{const{createHeifAdapter}=await load();const a=createHeifAdapter({nativeProbe:async()=>false,nativeDecode:async()=>{throw new Error('must not run');},wasmDecode:async()=>frame()});assert.equal((await a.process(job())).decodeRoute,'wasm');});
test('F05 adapter never retries hostile bytes through WASM after native decode starts and fails',async()=>{const{createHeifAdapter}=await load();let wasm=0;const a=createHeifAdapter({nativeProbe:async()=>true,nativeDecode:async()=>{throw new Error('decode');},wasmDecode:async()=>{wasm++;return frame();}});await assert.rejects(()=>a.process(job()),/heif_decode_failed/);assert.equal(wasm,0);});
test('F05 adapter rejects bad MIME cancellation and non-canonical decoder output',async()=>{const{createHeifAdapter}=await load();const a=createHeifAdapter({nativeProbe:async()=>false,nativeDecode:async()=>frame(),wasmDecode:async()=>({width:1600,height:1200,colorSpace:'display-p3'})});await assert.rejects(()=>a.process({...job(),mimeType:'image/jpeg'}),/heif_container_invalid/);await assert.rejects(()=>a.process({...job(),signal:{aborted:true}}),/cancelled/);await assert.rejects(()=>a.process(job()),/heif_decode_failed/);});
test('F05 worker message transfers the source ArrayBuffer as sole media ownership transfer',async()=>{const{buildWorkerTransfer}=await load();const j=job();const t=buildWorkerTransfer(j);assert.equal(t.message.type,'process');assert.equal(t.message.job.jobId,'job_1');assert.equal(t.message.job.bytes,j.bytes);assert.equal(t.message.job.mimeType,'image/heic');assert.deepEqual(t.message.job.transform,j.transform);assert.deepEqual(t.message.job.policy,POLICY);assert.deepEqual(t.transfer,[j.bytes]);assert.equal('filename' in t.message.job,false);assert.equal('token' in t.message.job,false);assert.equal('url' in t.message.job,false);assert.equal(Object.isFrozen(t.message),true);assert.equal(Object.isFrozen(t.message.job),true);});
