'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const{pathToFileURL}=require('node:url');
const url=pathToFileURL(path.resolve(__dirname,'../scripts/media/server/f05-derivative-gate.js')).href;async function load(){return import(`${url}?x=${Date.now()}-${Math.random()}`);}
const SHA='a'.repeat(64);const jpeg=Uint8Array.from([0xff,0xd8,0xff,0xdb,1,2,3,0xff,0xd9]);
function passport(overrides={}){return{schemaVersion:'F05_MEDIA_PASSPORT_V1',mediaPolicyVersion:'F05_BPLUS_V1',outputMime:'image/jpeg',width:1600,height:1200,sizeBytes:jpeg.byteLength,sha256:SHA,...overrides};}
function ports(overrides={}){return{authorizeAdMedia:async()=>true,sha256:async()=>SHA,inspectCandidate:async()=>({mime:'image/jpeg',width:1600,height:1200,hasForbiddenMetadata:false,isPolyglot:false}),rewriteCanonical:async()=>({bytes:jpeg}),auditSecurityEvent:async()=>{},...overrides};}
test('F05 server gate independently rewrites and re-inspects a valid derivative',async()=>{const{verifyAndRewriteCandidate}=await load();let inspections=0;const p=ports({inspectCandidate:async()=>{inspections++;return{mime:'image/jpeg',width:1600,height:1200,hasForbiddenMetadata:false,isPolyglot:false};}});const r=await verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:jpeg,mediaPassport:passport()},p);assert.equal(inspections,2);assert.equal(r.ok,true);assert.equal(r.canonicalMime,'image/jpeg');assert.equal(r.width,1600);assert.equal(r.height,1200);assert.equal(r.sha256,SHA);assert.equal(Object.isFrozen(r),true);});
test('F05 server gate rejects direct bypass bad magic bad hash and unauthorized scope',async()=>{const{verifyAndRewriteCandidate}=await load();await assert.rejects(()=>verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:Uint8Array.from([1,2,3]),mediaPassport:passport()},ports()),/media_derivative_invalid/);await assert.rejects(()=>verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:jpeg,mediaPassport:passport({sha256:'b'.repeat(64)})},ports()),/media_derivative_invalid/);await assert.rejects(()=>verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:jpeg,mediaPassport:passport()},ports({authorizeAdMedia:async()=>false})),/media_derivative_invalid/);});
test('F05 server gate rejects dimensions metadata polyglot and non-4:3 before publication',async()=>{const{verifyAndRewriteCandidate}=await load();for(const inspection of [{mime:'image/jpeg',width:1601,height:1200,hasForbiddenMetadata:false,isPolyglot:false},{mime:'image/jpeg',width:1000,height:1000,hasForbiddenMetadata:false,isPolyglot:false},{mime:'image/jpeg',width:1600,height:1200,hasForbiddenMetadata:true,isPolyglot:false},{mime:'image/jpeg',width:1600,height:1200,hasForbiddenMetadata:false,isPolyglot:true}])await assert.rejects(()=>verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:jpeg,mediaPassport:passport()},ports({inspectCandidate:async()=>inspection})),/media_derivative_invalid/);});
test('F05 server gate rejects rewrite output that is not a canonical JPEG/WebP image',async()=>{const{verifyAndRewriteCandidate}=await load();await assert.rejects(()=>verifyAndRewriteCandidate({actor:{id:'u1'},adScope:{adId:'a1'},candidateBytes:jpeg,mediaPassport:passport()},ports({rewriteCanonical:async()=>({bytes:Uint8Array.from([0x3c,0x68,0x74,0x6d,0x6c,0x3e])})})),/media_derivative_rewrite_failed/);});
