'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const{pathToFileURL}=require('node:url');
const opUrl=pathToFileURL(path.resolve(__dirname,'../scripts/media/server/f05-media-operation.js')).href;async function load(){return import(`${opUrl}?x=${Date.now()}-${Math.random()}`);}
function request(overrides={}){return{actorId:'principal_user1',tenantId:'tenant_global',listingId:'listing_ad1',listingPrincipalId:'principal_user1',countryCode:'JO',countrySealVersion:'seal_jo_1',...overrides};}
function ports(){const db=new Map();let n=0;return{resolveDataResidency:async c=>c==='JO'?{region:'eu-west-approved'}:null,newOperationId:()=>`media_operation_${++n}`,newTempObjectId:()=>`media_temp_${n}`,getOperation:async id=>db.get(id)||null,putOperation:async r=>{db.set(r.operationId,r);return r;}};}
test('F05 begins a private bounded operation and requires residency',async()=>{const{beginMediaOperation}=await load();const p=ports();const r=await beginMediaOperation(request(),p,Date.parse('2026-08-14T10:00:00Z'));assert.equal(r.state,'reserved');assert.equal(r.candidatePublic,false);assert.equal(r.dataResidencyRegion,'eu-west-approved');assert.equal(r.tempExpiresAt,'2026-08-15T10:00:00.000Z');await assert.rejects(()=>beginMediaOperation(request({countryCode:'ZZ'}),p,Date.now()),/media_residency_required/);});
test('F05 retries are idempotent and cross-scope replay is denied',async()=>{const{beginMediaOperation}=await load();const p=ports();const first=await beginMediaOperation(request(),p,Date.parse('2026-08-14T10:00:00Z'));const retry=await beginMediaOperation(request({operationId:first.operationId}),p,Date.parse('2026-08-14T10:01:00Z'));assert.deepEqual(retry,first);await assert.rejects(()=>beginMediaOperation(request({listingId:'listing_other',operationId:first.operationId}),p,Date.now()),/media_operation_replay/);});
test('F05 operation state transitions are forward-only',async()=>{const{transitionMediaOperation}=await load();const base=Object.freeze({operationId:'media_operation_1',state:'reserved'});const received=transitionMediaOperation(base,'candidate_received');assert.equal(received.state,'candidate_received');assert.equal(transitionMediaOperation(received,'verified').state,'verified');assert.throws(()=>transitionMediaOperation(received,'reserved'),/media_operation_state_invalid/);});
test('F05 builds valid V13.1 asset and derivative manifests from rewritten canonical bytes',async()=>{const{buildV13CanonicalManifests}=await load();const result=buildV13CanonicalManifests({...request(),operationId:'media_operation_1',createdAt:'2026-08-14T10:00:00.000Z'},{canonicalMime:'image/webp',width:1600,height:1200,sizeBytes:200000,sha256:'a'.repeat(64)},{assetId:'media_asset_1',derivativeId:'media_derivative_1',objectRef:'media_object_ref_1',storageRevision:1},'2026-08-14T10:01:00.000Z');assert.equal(result.asset.ok,true);assert.equal(result.derivative.ok,true);assert.equal(result.asset.value.contract.name,'V13.1_MEDIA_ASSET_MANIFEST');assert.equal(result.derivative.value.contract.name,'V13.1_MEDIA_DERIVATIVE_MANIFEST');assert.equal(result.derivative.value.objectRef,'media_object_ref_1');});
