'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const verifierPath=path.join(root,'scripts/launch/verify-f09-launch-evidence.cjs');const evidencePath=path.join(root,'config/launch/evidence/f09-bounded-ai.json');
function load(){return JSON.parse(fs.readFileSync(evidencePath,'utf8'));}
function complete(){const e=load();e.status='PASS';e.release={sha:'a'.repeat(40),artifactSha256:'b'.repeat(64)};for(const n of ['sovereignKernel','nexusBoundary','focusedTests','nexusIntegration','protectedExactHead']){e[n].status='PASS';e[n].evidence=['proof'];}e.nexusBoundary.digitalZeroBenefit=true;e.nexusBoundary.sovereignActionsDenied=true;e.protectedExactHead.runnerExecuted=true;e.protectedExactHead.sha=e.release.sha;e.launchGatePass=true;return e;}
test('current F09 evidence stays fail-closed',()=>{const {verifyF09LaunchEvidence}=require(verifierPath);const r=verifyF09LaunchEvidence(load(),{});assert.equal(r.ok,true,r.errors.join('\n'));assert.equal(r.launchGatePass,false);assert.ok(r.blockingSections.includes('nexusIntegration'));assert.ok(r.blockingSections.includes('protectedExactHead'));});
test('F09 boundary PASS requires zero-benefit and sovereign-action denial',()=>{const {verifyF09LaunchEvidence}=require(verifierPath);const e=complete();e.nexusBoundary.digitalZeroBenefit=false;const r=verifyF09LaunchEvidence(e,{currentHeadSha:e.release.sha});assert.equal(r.ok,false);assert.ok(r.errors.includes('F09_BOUNDARY_PASS_REQUIRES_ZERO_BENEFIT_AND_SOVEREIGN_DENIAL'));});
test('F09 protected PASS requires runner execution',()=>{const {verifyF09LaunchEvidence}=require(verifierPath);const e=complete();e.protectedExactHead.runnerExecuted=false;const r=verifyF09LaunchEvidence(e,{currentHeadSha:e.release.sha});assert.equal(r.ok,false);assert.ok(r.errors.includes('F09_PROTECTED_PASS_REQUIRES_RUNNER_EXECUTION'));});
test('F09 cannot claim PASS without all sections and release identity',()=>{const {verifyF09LaunchEvidence}=require(verifierPath);const e=load();e.status='PASS';e.launchGatePass=true;const r=verifyF09LaunchEvidence(e,{});assert.equal(r.ok,false);assert.ok(r.errors.includes('F09_PASS_REQUIRES_RELEASE_IDENTITY'));assert.ok(r.errors.includes('F09_PASS_REQUIRES_ALL_SECTIONS_PASS'));});
test('fully evidenced F09 exact release can pass',()=>{const {verifyF09LaunchEvidence}=require(verifierPath);const e=complete();const r=verifyF09LaunchEvidence(e,{currentHeadSha:e.release.sha});assert.equal(r.ok,true,r.errors.join('\n'));assert.equal(r.launchGatePass,true);});
