const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');
const verify=()=>import(pathToFileURL(path.resolve(__dirname,'../scripts/cleanup/phoenix-verify.mjs')).href+`?${Math.random()}`);const passport=()=>import(pathToFileURL(path.resolve(__dirname,'../scripts/cleanup/phoenix-passport.mjs')).href+`?${Math.random()}`);
function manifest(objects,coverage=[{plane:'repository',state:'OBSERVED'}],digest='a'){return {environment_identity:'env',manifest_digest:digest.repeat(64).slice(0,64),protected_namespaces:['protected'],objects,plane_coverage:coverage,filesystem:{capacity:{free_bytes:10,total_bytes:100},inodes:{free_inodes:10,total_inodes:100}}};}
const cert=id=>({schema_version:'TIGER-AION-DISPOSAL-CERTIFICATE-1',asset_id:id,content_digest:'c'.repeat(64)});
test('collateral sibling deletion fails even if intended target was removed',async()=>{const v=await verify();const before=manifest([{id:'target',path:'tmp/target',sha256:'1'},{id:'sibling',path:'tmp/sibling',sha256:'2'}],undefined,'a');const after=manifest([],undefined,'b');const r=v.verifyCleanup(before,['target'],after,[cert('target')]);assert.equal(r.status,'FAILED_VERIFICATION');assert.deepEqual(r.unexpected_deletions,['sibling']);});
test('protected mutation or deletion fails verification',async()=>{const v=await verify();const before=manifest([{id:'p',path:'protected/evidence',sha256:'1'}],undefined,'a');const after=manifest([{id:'p',path:'protected/evidence',sha256:'2'}],undefined,'b');const r=v.verifyCleanup(before,[],after,[]);assert.equal(r.status,'FAILED_VERIFICATION');assert.deepEqual(r.protected_changes,['p']);});
test('target deletion requires AION certificate',async()=>{const v=await verify();const before=manifest([{id:'target',path:'tmp/target',sha256:'1'}],undefined,'a');const after=manifest([],undefined,'b');assert.equal(v.verifyCleanup(before,['target'],after,[]).status,'FAILED_VERIFICATION');assert.equal(v.verifyCleanup(before,['target'],after,[cert('target')]).status,'VERIFIED');});
test('full-safe passport with blocked remote plane cannot be green full scope',async()=>{const v=await verify();const p=await passport();const before=manifest([],undefined,'a');const coverage=[{plane:'repository',state:'OBSERVED'},{plane:'codespaces',state:'BLOCKED_CAPABILITY'}];const after=manifest([],coverage,'b');const r=v.verifyCleanup(before,[],after,[]);assert.equal(r.status,'VERIFIED');assert.equal(r.coverage_complete,false);const pass=p.createCleanupPassport({scope:'full-safe',beforeManifest:before,afterManifest:after,shadowPlanDigest:'s'.repeat(64),porRoot:'p'.repeat(64),verification:r});assert.equal(pass.final_status,'PARTIAL');assert.notEqual(pass.final_status,'GREEN_FULL_SCOPE');});
test('clean scoped verification produces GREEN_SCOPED passport',async()=>{const v=await verify();const p=await passport();const before=manifest([{id:'target',path:'tmp/target',sha256:'1'}],undefined,'a');const after=manifest([],undefined,'b');const r=v.verifyCleanup(before,['target'],after,[cert('target')]);const pass=p.createCleanupPassport({scope:'scoped',beforeManifest:before,afterManifest:after,shadowPlanDigest:'s'.repeat(64),porRoot:'p'.repeat(64),aionCertificates:[cert('target')],verification:r});assert.equal(pass.final_status,'GREEN_SCOPED');assert.equal(pass.unexpected_deletion_count,0);assert.match(pass.passport_digest,/^[a-f0-9]{64}$/);});
