const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');const mod=()=>import(pathToFileURL(path.join(root,'scripts/cleanup/phoenix-headroom-gate.mjs')).href+`?${Math.random()}`);const policyPath=path.join(root,'project-control/cleanup/phoenix-storage-pressure-policy.v1.json');
function observation({free=8*1024**3,total=16*1024**3,ifree=500000,itotal=1000000}={}){return {filesystem:{capacity:{available:true,free_bytes:free,total_bytes:total},inodes:{available:true,free_inodes:ifree,total_inodes:itotal}}};}
test('policy loads with five supported operation categories',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);assert.deepEqual(Object.keys(p.operations).sort(),['dependency_install','docker_build','heavy_rehearsal','quality_gate','supabase_start']);assert.ok(p.safety_factor>=1);});
test('healthy capacity passes using policy projection',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);assert.equal(m.checkHeadroom(observation(),'quality_gate',{},p).state,'GREEN_HEADROOM');});
test('low bytes or projected growth blocks',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);assert.equal(m.checkHeadroom(observation({free:600*1024**2}),'quality_gate',{},p).state,'BLOCKED_STORAGE_PRESSURE');assert.equal(m.checkHeadroom(observation(),'docker_build',{projected_growth_bytes:20*1024**3,projected_inode_growth:1},p).state,'BLOCKED_STORAGE_PRESSURE');});
test('low inodes blocks',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);const r=m.checkHeadroom(observation({ifree:30000}),'quality_gate',{},p);assert.equal(r.state,'BLOCKED_STORAGE_PRESSURE');assert.ok(r.reasons.some(x=>x.includes('INODES')));});
test('insufficient observation and invalid projection fail closed',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);assert.equal(m.checkHeadroom({filesystem:{capacity:{available:false},inodes:{available:true}}},'quality_gate',{},p).state,'BLOCKED_INSUFFICIENT_OBSERVATION');assert.equal(m.checkHeadroom(observation(),'quality_gate',{projected_growth_bytes:-1},p).state,'BLOCKED_INVALID_PROJECTION');});
test('category mismatch and unknown operation are blocked',async()=>{const m=await mod();const p=m.loadStoragePressurePolicy(policyPath);assert.equal(m.checkHeadroom(observation(),'quality_gate',{category:'container_build'},p).state,'BLOCKED_CATEGORY_MISMATCH');assert.equal(m.checkHeadroom(observation(),'unknown',{},p).state,'BLOCKED_UNKNOWN_OPERATION');});
