const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');
const mod=()=>import(pathToFileURL(path.resolve(__dirname,'../scripts/cleanup/phoenix-shadow-plan.mjs')).href+`?${Math.random()}`);
const P='p'.repeat(64),O='o'.repeat(64),M='m'.repeat(64);
function manifest(){return {environment_identity:'env',manifest_digest:M,policy_identity:{policy_sha256:P,owner_decision_sha256:O},protected_namespaces:['authority'],objects:[{id:'file:a',path:'tmp/a',sha256:'aaa'},{id:'file:b',path:'tmp/b',sha256:'bbb'}]};}
function por(){return [{candidate_id:'file:a',state:'RECLAIM_ELIGIBLE',requires_aion_disposal_gate:true,por_digest:'x'.repeat(64)}];}
test('trusted in-process plan yields exact target lease',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env',maxAgeMs:1000});const p=m.createShadowPlan(c,manifest(),por(),new Date(0));const lease=m.consumeShadowTarget(p,manifest(),'file:a',new Date(500));assert.equal(lease.state,'TRUSTED_TARGET_LEASE');assert.equal(lease.target_digest,'aaa');assert.equal(lease.requires_aion_disposal_gate,true);});
test('serialized/JSON-cloned plan is evidence only',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env'});const p=m.createShadowPlan(c,manifest(),por(),new Date(0));const clone=JSON.parse(JSON.stringify(p));assert.equal(m.consumeShadowTarget(clone,manifest(),'file:a',new Date(1)).state,'UNTRUSTED_PLAN_BLOCKED');});
test('stale, wildcard and unitemized targets fail closed',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env',maxAgeMs:10});const p=m.createShadowPlan(c,manifest(),por(),new Date(0));assert.equal(m.consumeShadowTarget(p,manifest(),'file:a',new Date(11)).state,'STALE_PLAN_BLOCKED');assert.equal(m.consumeShadowTarget(p,manifest(),'*',new Date(1)).state,'TARGET_ID_BLOCKED');assert.equal(m.consumeShadowTarget(p,manifest(),'file:b',new Date(1)).state,'UNITEMIZED_TARGET_BLOCKED');});
test('manifest or authority digest drift blocks',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env'});const p=m.createShadowPlan(c,manifest(),por(),new Date(0));const d=manifest();d.manifest_digest='z'.repeat(64);assert.equal(m.consumeShadowTarget(p,d,'file:a',new Date(1)).state,'MANIFEST_DRIFT_BLOCKED');const a=manifest();a.policy_identity.policy_sha256='q'.repeat(64);assert.equal(m.consumeShadowTarget(p,a,'file:a',new Date(1)).state,'AUTHORITY_DRIFT_BLOCKED');});
test('target replacement under same id/path or same path/new id is blocked',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env'});const p=m.createShadowPlan(c,manifest(),por(),new Date(0));const replaced=manifest();replaced.objects[0]={id:'file:a',path:'tmp/a',sha256:'evil'};assert.equal(m.consumeShadowTarget(p,replaced,'file:a',new Date(1)).state,'TARGET_DRIFT_BLOCKED');const reincarnated=manifest();reincarnated.objects[0]={id:'file:new',path:'tmp/a',sha256:'aaa'};assert.equal(m.consumeShadowTarget(p,reincarnated,'file:a',new Date(1)).state,'TARGET_DRIFT_BLOCKED');});
test('create rejects foreign context and authority mismatch',async()=>{const m=await mod();const c=m.createTrustedShadowContext({policyDigest:P,ownerDecisionDigest:O,environmentIdentity:'env'});assert.throws(()=>m.createShadowPlan({...c},manifest(),por(),new Date(0)),/UNTRUSTED/);const bad=manifest();bad.policy_identity.owner_decision_sha256='x';assert.throws(()=>m.createShadowPlan(c,bad,por(),new Date(0)),/AUTHORITY_DIGEST_MISMATCH/);});
