const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {pathToFileURL}=require('node:url');const root=path.resolve(__dirname,'..');
const load=n=>import(pathToFileURL(path.join(root,'scripts/cleanup/remote',n)).href+`?${Math.random()}`);
test('capability states distinguish write, read-only, unavailable and blocked',async()=>{const c=await load('capability.mjs');assert.equal(c.capabilityFor({listArtifacts(){},deleteArtifact(){}},'listArtifacts','deleteArtifact'),'READ_WRITE');assert.equal(c.capabilityFor({listArtifacts(){}},'listArtifacts','deleteArtifact'),'READ_ONLY');assert.equal(c.capabilityFor({unavailable:true},'listArtifacts','deleteArtifact'),'UNAVAILABLE');assert.equal(c.capabilityFor({},'listArtifacts','deleteArtifact'),'BLOCKED_CAPABILITY');});
test('artifact adapter paginates live objects and preserves retention metadata',async()=>{const m=await load('github-actions-artifacts.mjs');let calls=0;const a=m.createGitHubActionsArtifactsAdapter({async listArtifacts({cursor}){calls++;return cursor===null?{items:[{id:2,name:'b',retention_days:7}],next_cursor:'n'}:{items:[{id:1,name:'a',expires_at:'x'}],next_cursor:null};}});assert.equal(a.capability(),'READ_ONLY');const o=await a.observe();assert.equal(calls,2);assert.deepEqual(o.objects.map(x=>x.id),['artifact:1','artifact:2']);assert.equal(o.objects[1].retention_metadata,7);});
test('cache, codespace and prebuild adapters expose stable live IDs',async()=>{const cache=(await load('github-actions-cache.mjs')).createGitHubActionsCacheAdapter({async listCaches(){return{items:[{id:4,key:'k'}],next_cursor:null}}});const codes=(await load('github-codespaces.mjs')).createGitHubCodespacesAdapter({async listCodespaces(){return{items:[{name:'c1',state:'Available'}],next_cursor:null}}});const pre=(await load('github-prebuilds.mjs')).createGitHubPrebuildsAdapter({async listPrebuilds(){return{items:[{id:9,state:'ready'}],next_cursor:null}}});assert.equal((await cache.observe()).objects[0].id,'cache:4');assert.equal((await codes.observe()).objects[0].id,'codespace:c1');assert.equal((await pre.observe()).objects[0].id,'prebuild:9');});
test('missing remote action is explicit blocked capability and never full invisible skip',async()=>{const m=await load('github-codespaces.mjs');const a=m.createGitHubCodespacesAdapter({});const o=await a.observe();assert.equal(o.state,'BLOCKED_CAPABILITY');assert.equal(o.plane,'codespaces');assert.deepEqual(o.objects,[]);});
test('mutation is unavailable for read-only adapter',async()=>{const m=await load('github-actions-cache.mjs');const a=m.createGitHubActionsCacheAdapter({async listCaches(){return{items:[],next_cursor:null}}});const r=await a.disposeWithAionEvidence('cache:1',{verified_stage:'VERIFY',requires_aion_disposal_gate:true,lease_digest:'l',target_id:'cache:1'});assert.equal(r.state,'READ_ONLY');assert.equal(r.disposed,false);});
test('read-write mutation requires exact AION VERIFY evidence and target binding',async()=>{const m=await load('github-actions-artifacts.mjs');let deleted=0;const a=m.createGitHubActionsArtifactsAdapter({async listArtifacts(){return{items:[],next_cursor:null}},async deleteArtifact(x){deleted++;return x;}});await assert.rejects(()=>a.disposeWithAionEvidence('artifact:1',{}),/AION_EVIDENCE_REQUIRED/);await assert.rejects(()=>a.disposeWithAionEvidence('artifact:1',{verified_stage:'VERIFY',requires_aion_disposal_gate:true,lease_digest:'l',target_id:'artifact:2'}),/TARGET_MISMATCH/);const r=await a.disposeWithAionEvidence('artifact:1',{verified_stage:'VERIFY',requires_aion_disposal_gate:true,lease_digest:'l',target_id:'artifact:1'});assert.equal(r.state,'DISPOSAL_REQUESTED');assert.equal(deleted,1);});
test('pagination loop is rejected',async()=>{const c=await load('capability.mjs');await assert.rejects(()=>c.collectPages(async()=>({items:[],next_cursor:'same'})),/PAGINATION_LOOP/);});
