'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const migrationPath = path.join(__dirname, '..', 'supabase', 'migrations', '20260813170000_soa_owner_security_foundation.sql');
function sql() { assert.equal(fs.existsSync(migrationPath), true, 'SOA owner security migration must exist'); return fs.readFileSync(migrationPath, 'utf8').toLowerCase(); }
const tables = ['soa_owner_authority_bindings','soa_owner_public_profiles','soa_owner_private_vault','soa_owner_audit_events','soa_owner_authorization_leases','soa_owner_security_state'];
test('SOA creates physically separate owner security boundaries', () => { const source = sql(); for (const table of tables) assert.match(source, new RegExp(`create\\s+table\\s+if\\s+not\\s+exists\\s+public\\.${table}\\b`)); assert.doesNotMatch(source, /insert\s+into\s+public\.soa_owner_/i); });
test('SOA states are explicit and legacy roles are not authority', () => { const source = sql(); for (const state of ['pending','verified','active','suspended','revoked','draft','reviewed','published','withdrawn']) assert.match(source, new RegExp(`'${state}'`)); assert.doesNotMatch(source, /super_admin\s*['"]/i); assert.doesNotMatch(source, /role\s*=\s*['"]owner['"]/i); });
test('SOA enforces RLS and FORCE RLS', () => { const source = sql(); for (const table of tables) { assert.match(source, new RegExp(`alter\\s+table\\s+public\\.${table}\\s+enable\\s+row\\s+level\\s+security`)); assert.match(source, new RegExp(`alter\\s+table\\s+public\\.${table}\\s+force\\s+row\\s+level\\s+security`)); } });
test('private surfaces deny browser roles and public projection is column-allowlisted read-only', () => { const source = sql(); for (const table of tables.filter(t => t !== 'soa_owner_public_profiles')) assert.match(source, new RegExp(`revoke\\s+all\\s+on\\s+table\\s+public\\.${table}\\s+from\\s+public,\\s*anon,\\s*authenticated`)); assert.doesNotMatch(source, /grant\s+select\s+on\s+table\s+public\.soa_owner_public_profiles\s+to\s+anon,\s*authenticated/); const grant = source.match(/grant\s+select\s*\(([^)]*)\)\s+on\s+table\s+public\.soa_owner_public_profiles\s+to\s+anon,\s*authenticated/); assert.ok(grant, 'column-level public SELECT grant must exist'); const columns = grant[1].split(',').map((value) => value.trim()).filter(Boolean).sort(); assert.deepEqual(columns, ['approved_public_contact_url','public_avatar_url','public_bio','public_country_code','public_display_name','public_title','verified_owner_badge'].sort()); for (const forbidden of ['owner_authority_id','published_by','created_at','updated_at','public_version']) assert.equal(columns.includes(forbidden), false, forbidden); assert.match(source, /publication_status\s*=\s*'published'/); });
test('audit is append-only and no SECURITY DEFINER is used', () => { const source = sql(); assert.match(source, /before\s+update\s+or\s+delete\s+on\s+public\.soa_owner_audit_events/); assert.match(source, /raise\s+exception\s+'soa_owner_audit_append_only'/); assert.doesNotMatch(source, /security\s+definer/); });
test('L4 lease is exact-bound, short-lived and single-use', () => { const source = sql(); for (const field of ['owner_authority_id','clerk_user_id','session_id','action_code','target_resource','environment','policy_version','release_digest','nonce','issued_at','expires_at','consumed_at']) assert.match(source, new RegExp(`\\b${field}\\b`)); assert.match(source, /unique\s*\(nonce\)/); assert.match(source, /interval\s+'120 seconds'/); assert.match(source, /issued_at\s+timestamptz\s+not\s+null\s+default\s+clock_timestamp\(\)/); });
test('private vault stores encrypted envelopes, not plaintext PII columns', () => { const source = sql(); assert.match(source, /encrypted_payload\s+bytea\s+not\s+null/); assert.match(source, /key_version\s+text\s+not\s+null/); assert.doesNotMatch(source, /private_email\s+text|private_phone\s+text|legal_full_name\s+text/); });
