'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createOwnerCommandBoundary } = require('../scripts/security/soa/owner-command-boundary.js');
const NOW = '2026-08-13T13:01:00.000Z';
function context(overrides = {}) { return { authority: { ownerAuthorityId: 'oa_1', status: 'ACTIVE', clerkUserId: 'user_owner', ...(overrides.authority || {}) }, security: { killSwitch: false, holdState: 'CLEAR', recoveryState: 'NONE', l4Enabled: true, ...(overrides.security || {}) }, auth: { clerkUserId: 'user_owner', sessionId: 'sess_1', sessionAuthenticated: true, mfaVerifiedAt: '2026-08-13T13:00:00.000Z', reverifiedAt: '2026-08-13T13:00:00.000Z', ...(overrides.auth || {}) }, policyVersion: 'SOA-2026.1' }; }
function request(overrides = {}) { return { authenticatedClerkUserId: 'user_owner', sessionId: 'sess_1', actionCode: 'UPDATE_PUBLIC_PROFILE', targetResource: 'owner-profile', environment: 'STAGING', correlationId: 'corr_1', idempotencyKey: 'idem_1', releaseDigest: 'sha256:abc', payload: { publicDisplayName: 'Owner' }, ...overrides }; }
function harness({ trusted = context(), lease, committed = true, consume = true } = {}) { const calls = []; let persisted; let audits = []; const tx = { persistOwnerCommand: async (value) => { calls.push('persist'); persisted = value; return { ok: true }; }, appendOwnerAudit: async (value) => { calls.push('audit'); audits.push(value); return { eventId: `evt_${audits.length}` }; }, loadAuthorizationLease: async () => { calls.push('lease-load'); return lease; }, consumeAuthorizationLease: async () => { calls.push('lease-consume'); return consume; } }; const boundary = createOwnerCommandBoundary({ loadOwnerContext: async () => { calls.push('context'); return trusted; }, runTransaction: async (work) => { calls.push('tx'); return { committed, value: await work(tx) }; }, clock: () => NOW }); return { boundary, calls, get persisted() { return persisted; }, get audits() { return audits; } }; }

test('public owner updates use a strict allowlist and reject private fields before persistence', async () => { const h = harness(); const bad = await h.boundary.execute(request({ payload: { publicDisplayName: 'Owner', privateEmail: 'secret@example.invalid' } })); assert.deepEqual(bad, { ok: false, code: 'ERR_OWNER_PUBLIC_FIELDS_INVALID' }); assert.equal(h.calls.includes('context'), false); const good = await h.boundary.execute(request({ payload: { publicDisplayName: 'Owner', publicTitle: 'Founder' } })); assert.equal(good.ok, true); assert.deepEqual(h.persisted.payload, { publicDisplayName: 'Owner', publicTitle: 'Founder' }); });

test('private vault accepts only a sealed encrypted envelope and requires fresh L3 reverification', async () => { const raw = harness(); const denied = await raw.boundary.execute(request({ actionCode: 'UPDATE_PRIVATE_VAULT', targetResource: 'owner-vault', payload: { privateEmail: 'secret@example.invalid' } })); assert.equal(denied.code, 'ERR_OWNER_VAULT_ENVELOPE_REQUIRED'); const sealedPayload = { encryptedPayload: 'ciphertext-not-plaintext', keyVersion: 'kms-v1', cipherSuite: 'AES-256-GCM', classification: 'OWNER_RESTRICTED', retentionPolicy: 'OWNER-LIFECYCLE', dataVersion: 1 }; const stale = harness({ trusted: context({ auth: { reverifiedAt: '2026-08-13T12:50:00.000Z' } }) }); assert.equal((await stale.boundary.execute(request({ actionCode: 'UPDATE_PRIVATE_VAULT', targetResource: 'owner-vault', payload: sealedPayload }))).code, 'ERR_OWNER_REVERIFICATION_REQUIRED'); const good = harness(); assert.equal((await good.boundary.execute(request({ actionCode: 'UPDATE_PRIVATE_VAULT', targetResource: 'owner-vault', payload: sealedPayload }))).ok, true); assert.deepEqual(good.persisted.payload, sealedPayload); });

test('trusted server identity/session binding is exact and browser role claims are irrelevant', async () => { const h = harness({ trusted: context({ auth: { clerkUserId: 'user_other' } }) }); const result = await h.boundary.execute(request({ legacyRole: 'super_admin' })); assert.equal(result.code, 'ERR_OWNER_TRUSTED_CONTEXT_MISMATCH'); assert.equal(h.calls.includes('tx'), false); });

test('L4 requires an exact unexpired single-use lease and audit before plus after execution', async () => { const baseReq = request({ actionCode: 'ROTATE_OWNER_SECURITY_POLICY', targetResource: 'owner-security-policy', leaseId: 'lease_1', payload: { nextPolicyVersion: 'SOA-2026.2' } }); const exactLease = { leaseId: 'lease_1', ownerAuthorityId: 'oa_1', clerkUserId: 'user_owner', sessionId: 'sess_1', actionCode: 'ROTATE_OWNER_SECURITY_POLICY', targetResource: 'owner-security-policy', environment: 'STAGING', policyVersion: 'SOA-2026.1', releaseDigest: 'sha256:abc', nonce: 'nonce_1', issuedAt: '2026-08-13T13:00:30.000Z', expiresAt: '2026-08-13T13:02:00.000Z', consumedAt: null, revokedAt: null }; const mismatch = harness({ lease: { ...exactLease, targetResource: 'other' } }); assert.equal((await mismatch.boundary.execute(baseReq)).code, 'ERR_OWNER_L4_LEASE_MISMATCH'); assert.equal(mismatch.calls.includes('persist'), false); const replay = harness({ lease: exactLease, consume: false }); assert.equal((await replay.boundary.execute(baseReq)).code, 'ERR_OWNER_L4_LEASE_REPLAY'); assert.equal(replay.calls.includes('persist'), false); const good = harness({ lease: exactLease }); const result = await good.boundary.execute(baseReq); assert.equal(result.ok, true); assert.deepEqual(good.calls.filter((v) => ['audit','lease-consume','persist'].includes(v)), ['audit','lease-consume','persist','audit']); });

test('L4 lease is policy-bound, server-time bounded, and never valid for more than 120 seconds', async () => {
  const baseReq = request({ actionCode: 'ROTATE_OWNER_SECURITY_POLICY', targetResource: 'owner-security-policy', leaseId: 'lease_1', payload: { nextPolicyVersion: 'SOA-2026.2' } });
  const exactLease = { leaseId: 'lease_1', ownerAuthorityId: 'oa_1', clerkUserId: 'user_owner', sessionId: 'sess_1', actionCode: 'ROTATE_OWNER_SECURITY_POLICY', targetResource: 'owner-security-policy', environment: 'STAGING', policyVersion: 'SOA-2026.1', releaseDigest: 'sha256:abc', nonce: 'nonce_1', issuedAt: '2026-08-13T13:00:30.000Z', expiresAt: '2026-08-13T13:02:00.000Z', consumedAt: null, revokedAt: null };
  for (const lease of [
    { ...exactLease, policyVersion: 'SOA-OLD' },
    { ...exactLease, issuedAt: '2026-08-13T12:59:00.000Z', expiresAt: '2026-08-13T13:02:00.000Z' },
    { ...exactLease, issuedAt: '2026-08-13T13:01:30.000Z' },
  ]) {
    const h = harness({ lease });
    const result = await h.boundary.execute(baseReq);
    assert.equal(result.code, 'ERR_OWNER_L4_LEASE_MISMATCH');
    assert.equal(h.calls.includes('persist'), false);
  }
});

test('uncommitted transaction never reports success and audit never contains command payload', async () => { const h = harness({ committed: false }); const result = await h.boundary.execute(request()); assert.equal(result.code, 'ERR_OWNER_ENFORCEMENT_FAILED'); const good = harness(); await good.boundary.execute(request({ payload: { publicDisplayName: 'Highly Sensitive Display Test' } })); const auditText = JSON.stringify(good.audits); assert.equal(auditText.includes('Highly Sensitive Display Test'), false); assert.equal(auditText.includes('payload'), false); });

test('SOA command boundary is pure and has no browser, credential, remote URL, or environment dependency', () => { const source = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'security', 'soa', 'owner-command-boundary.js'), 'utf8'); assert.doesNotMatch(source, /https?:\/\/|supabase\.co|service[_-]?role|postgres(?:ql)?:\/\/|process\.env|localStorage|sessionStorage|window\.|document\.|createClient/i); });
