'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const WORKFLOW_PATH = path.join(__dirname, '..', '.github', 'workflows', 'svef-release-candidate.yml');
const CHECKOUT_V7_SHA = '3d3c42e5aac5ba805825da76410c181273ba90b1';
const SETUP_NODE_V6_SHA = '249970729cb0ef3589644e2896645e5dc5ba9c38';
const SETUP_PYTHON_V6_SHA = 'ece7cb06caefa5fff74198d8649806c4678c61a1';
const ATTEST_V4_SHA = '508db95dd578ae2727ebd6217d5ba78e4fbda05d';
const UPLOAD_ARTIFACT_V4_SHA = 'ea165f8d65b6e75b540449e92b4886f43607fa02';

function workflow() {
  return fs.readFileSync(WORKFLOW_PATH, 'utf8');
}

test('SVEF provenance runs only in exact push/manual context with immutable actions', () => {
  const text = workflow();
  assert.doesNotMatch(text, /\bpull_request:/, 'PR OIDC context can resolve a synthetic merge SHA');
  assert.match(text, /push:[\s\S]*branches:[\s\S]*- main[\s\S]*- ['"]?feat\/svef-\*['"]?/);
  assert.match(text, /workflow_dispatch:[\s\S]*source_sha:/);
  assert.match(text, /permissions:\s*\n\s*contents:\s*read\s*\n\s*id-token:\s*write\s*\n\s*attestations:\s*write/);
  assert.match(text, new RegExp(`actions\\/checkout@${CHECKOUT_V7_SHA}`));
  assert.match(text, new RegExp(`actions\\/setup-node@${SETUP_NODE_V6_SHA}`));
  assert.match(text, new RegExp(`actions\\/setup-python@${SETUP_PYTHON_V6_SHA}`));
  assert.match(text, new RegExp(`actions\\/attest@${ATTEST_V4_SHA}`));
  assert.match(text, new RegExp(`actions\\/upload-artifact@${UPLOAD_ARTIFACT_V4_SHA}`));
});

test('workflow checks out and verifies the exact push SHA or validated manual SHA', () => {
  const text = workflow();
  assert.match(text, /SOURCE_SHA:\s*\$\{\{[\s\S]*github\.event_name\s*==\s*['"]workflow_dispatch['"][\s\S]*inputs\.source_sha[\s\S]*github\.sha[\s\S]*\}\}/);
  assert.match(text, /ref:\s*\$\{\{\s*env\.SOURCE_SHA\s*\}\}/);
  assert.match(text, /git rev-parse HEAD/);
  assert.match(text, /git rev-parse HEAD\^\{tree\}/);
  assert.match(text, /test\s+"\$actual_sha"\s*=\s*"\$SOURCE_SHA"/);
});

test('workflow builds the V14 candidate exactly once outside the repository', () => {
  const text = workflow();
  const builds = text.match(/^\s*python\s+tools\/vvip_public_release\.py\b/gm) || [];
  assert.equal(builds.length, 1, 'release workflow must have one and only one candidate build command');
  assert.match(text, /--output\s+"\$RUNNER_TEMP\/vvip-candidate"/);
  assert.match(text, /--source-sha\s+"\$SOURCE_SHA"/);
  assert.match(text, /--mode\s+candidate/);
  assert.doesNotMatch(text, /dist\/public|dist\/candidate/);
});

test('workflow creates SBOM materials and deterministic release bundle before attestation', () => {
  const text = workflow();
  assert.match(text, /sbom\.cdx\.json/);
  assert.match(text, /materials\.json/);
  assert.match(text, /release-bundle-manifest\.json/);
  assert.match(text, /release-bundle\.cjs/);
  assert.match(text, /tar\s+--sort=name/);
  assert.match(text, /--mtime=['"]UTC 1970-01-01['"]/);
  assert.match(text, /--owner=0/);
  assert.match(text, /--group=0/);
  assert.match(text, /--numeric-owner/);
  assert.match(text, /gzip\s+-n/);
  assert.match(text, /sha256sum[\s\S]*svef-release-bundle-/);
});

test('standard SLSA provenance is generated by GitHub instead of a caller-authored SLSA predicate', () => {
  const text = workflow();
  assert.doesNotMatch(text, /Generate exact-source SLSA provenance predicate/);
  assert.doesNotMatch(text, /predicate-type:\s*https:\/\/slsa\.dev\/provenance\/v1/);
  assert.doesNotMatch(text, /predicate-path:/);
  assert.doesNotMatch(text, /buildType:\s*['"]https:\/\/vvip-tiger\.example/);
  assert.match(text, /name:\s*Attest exact release bundle with GitHub SLSA provenance/);
  assert.match(text, /subject-path:\s*\$\{\{\s*runner\.temp\s*\}\}[\s\S]*svef-release-bundle-/);
});

test('workflow verifies signed provenance payload binds subject and resolved dependency to exact source', () => {
  const text = workflow();
  assert.match(text, /Verify signed provenance exact-source binding/);
  assert.match(text, /dsseEnvelope/);
  assert.match(text, /predicateType/);
  assert.match(text, /https:\/\/slsa\.dev\/provenance\/v1/);
  assert.match(text, /resolvedDependencies/);
  assert.match(text, /gitCommit/);
  assert.match(text, /SOURCE_SHA/);
  assert.match(text, /BUNDLE_DIGEST/);
  assert.match(text, /SVEF_ATTESTATION_SOURCE_MISMATCH/);
  assert.match(text, /SVEF_ATTESTATION_SUBJECT_MISMATCH/);
});

test('SBOM receives its own signed attestation and all evidence is retained', () => {
  const text = workflow();
  assert.match(text, /name:\s*Attest CycloneDX SBOM/);
  assert.match(text, /sbom-path:\s*\$\{\{\s*runner\.temp\s*\}\}\/svef-release-metadata\/sbom\.cdx\.json/);
  assert.match(text, /steps\.attest\.outputs\.bundle-path/);
  assert.match(text, /steps\.attest_sbom\.outputs\.bundle-path/);
  assert.match(text, /attestation-bundle\.json/);
  assert.match(text, /sbom-attestation-bundle\.json/);
  assert.match(text, /attestation-bundle\.sha256/);
  assert.match(text, /sbom-attestation-bundle\.sha256/);
  assert.match(text, /name:\s*svef-release-\$\{\{\s*env\.SOURCE_SHA\s*\}\}/);
  assert.match(text, /if-no-files-found:\s*error/);
});

test('release workflow is non-production and contains no uncontrolled upgrades or deployment authority', () => {
  const text = workflow();
  assert.doesNotMatch(text, /pip\s+install\s+--upgrade|python\s+-m\s+pip\s+install\s+--upgrade/i);
  assert.doesNotMatch(text, /environment:\s*(?:production|production-build|github-pages)/i);
  assert.doesNotMatch(text, /PRODUCTION_DB_PASSWORD|PRODUCTION_SERVICE_ROLE|SUPABASE_DB_PASSWORD|L4_ENABLED/);
  assert.doesNotMatch(text, /deploy-pages|upload-pages-artifact|supabase\s+db\s+push|supabase\s+functions\s+deploy/i);
});
