-- Feed posts table for public feed page persistence.
-- Run this migration in Supabase SQL editor.

create table if not exists public.feed_posts (
  id bigint generated by default as identity primary key,
  description text not null,
  media_kind text not null default 'all' check (media_kind in ('all', 'images', 'video')),
  visibility text not null default 'all' check (visibility in ('all', 'followed')),
  author_name text not null,
  author_handle text not null,
  like_count integer not null default 0,
  comment_count integer not null default 0,
  share_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.feed_posts enable row level security;

create policy if not exists "Anyone can read feed posts"
on public.feed_posts
for select
using (true);

create policy if not exists "Anyone can insert feed posts"
on public.feed_posts
for insert
with check (true);
