-- AI/analytics/ad-settings support tables for client runtime sync.
-- Run this migration in Supabase SQL editor.

create table if not exists public.feed_analytics_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text not null,
  payload_json jsonb not null default '{}'::jsonb,
  actor_handle text not null default 'autoparts.user',
  created_at timestamptz not null default now()
);

create index if not exists feed_analytics_events_created_at_idx
  on public.feed_analytics_events (created_at desc);

create index if not exists feed_analytics_events_actor_handle_idx
  on public.feed_analytics_events (actor_handle);

alter table public.feed_analytics_events enable row level security;

create policy if not exists "Anyone can read analytics events"
on public.feed_analytics_events
for select
using (true);

create policy if not exists "Anyone can insert analytics events"
on public.feed_analytics_events
for insert
with check (true);

create table if not exists public.ad_campaign_settings (
  id bigint generated by default as identity primary key,
  actor_handle text not null,
  location text not null default '',
  age_range text not null default '',
  interests text not null default '',
  budget text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists ad_campaign_settings_actor_handle_updated_at_idx
  on public.ad_campaign_settings (actor_handle, updated_at desc);

alter table public.ad_campaign_settings enable row level security;

create policy if not exists "Anyone can read ad campaign settings"
on public.ad_campaign_settings
for select
using (true);

create policy if not exists "Anyone can insert ad campaign settings"
on public.ad_campaign_settings
for insert
with check (true);
