#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
STATE_PATH = ROOT / "docs/owner-control/orchestrator/state.json"
LOG_PATH = ROOT / "docs/owner-control/orchestrator/log.ndjson"
CHECKPOINT_DIR = ROOT / "docs/owner-control/orchestrator/checkpoints"
CONFIG_PATH = ROOT / "scripts/orchestrator/p06_orchestrator_config.json"

ALLOWED_STATUSES = {
    "pending",
    "planning",
    "red",
    "implementing",
    "green",
    "preview",
    "pr_open",
    "reviewing",
    "merged",
    "post_merge_verified",
    "completed",
    "blocked",
    "owner_approval_required",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def append_log(event: str, status: str, phase: str, note: str = "") -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    row = {
        "ts": utc_now(),
        "phase": phase,
        "event": event,
        "status": status,
        "note": note,
    }
    with LOG_PATH.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def enforce_lock(state: dict[str, Any], phase: str) -> None:
    if state.get("emergency_stop", {}).get("active"):
        raise SystemExit("Emergency stop active. Use resume only after owner confirmation.")
    if phase != state.get("next_authorized_phase"):
        raise SystemExit("Phase mismatch with next authorized phase lock.")


def set_phase_status(state: dict[str, Any], phase: str, status: str) -> None:
    if status not in ALLOWED_STATUSES:
        raise SystemExit(f"Unsupported status: {status}")

    found = False
    for row in state.get("phase_states", []):
        if row.get("id") == phase:
            row["status"] = status
            row["updated_on"] = utc_now()
            found = True
            break

    if not found:
        state.setdefault("phase_states", []).append({
            "id": phase,
            "status": status,
            "updated_on": utc_now(),
            "evidence": [],
        })

    state["status"] = status
    state["updated_on"] = utc_now()


def create_checkpoint(state: dict[str, Any], phase: str, label: str) -> dict[str, Any]:
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    path = CHECKPOINT_DIR / f"{phase.lower()}-{label}.checkpoint.json"
    payload = {
        "phase": phase,
        "created_on": utc_now(),
        "status": state.get("status", "planning"),
        "checkpoint": label,
        "baseline": state.get("integrity", {}).get("last_verified_sha256", ""),
        "notes": [
            "Checkpoint generated by orchestrator",
            "Append-only audit log updated",
        ],
    }
    write_json(path, payload)
    digest = sha256_file(path)
    state["last_checkpoint"] = {
        "phase": phase,
        "path": str(path.relative_to(ROOT)).replace("\\", "/"),
        "sha256": digest,
        "created_on": payload["created_on"],
    }
    state.setdefault("integrity", {})["last_verified_sha256"] = digest
    return state


def cmd_status(_: argparse.Namespace) -> int:
    state = read_json(STATE_PATH)
    print(json.dumps(state, ensure_ascii=False, indent=2))
    return 0


def cmd_integrity_check(_: argparse.Namespace) -> int:
    state = read_json(STATE_PATH)
    cp = state.get("last_checkpoint", {})
    cp_path = ROOT / cp.get("path", "")
    if not cp_path.is_file():
        raise SystemExit("Integrity check failed: checkpoint file missing.")
    actual = sha256_file(cp_path)
    expected = cp.get("sha256", "")
    if actual != expected:
        raise SystemExit("Integrity check failed: sha256 mismatch.")
    print("integrity-check: OK")
    return 0


def cmd_resume(args: argparse.Namespace) -> int:
    state = read_json(STATE_PATH)
    phase = args.phase or state.get("current_phase", "P06")
    enforce_lock(state, phase)
    set_phase_status(state, phase, "implementing")
    create_checkpoint(state, phase, "resume")
    write_json(STATE_PATH, state)
    append_log("resume", "implementing", phase, "phase resumed")
    print(f"resume: {phase}")
    return 0


def cmd_emergency_stop(args: argparse.Namespace) -> int:
    state = read_json(STATE_PATH)
    phase = state.get("current_phase", "P06")
    state.setdefault("emergency_stop", {})["active"] = True
    state.setdefault("emergency_stop", {})["reason"] = args.reason
    set_phase_status(state, phase, "blocked")
    write_json(STATE_PATH, state)
    append_log("emergency-stop", "blocked", phase, args.reason)
    print("emergency-stop: active")
    return 0


def cmd_dry_run(args: argparse.Namespace) -> int:
    state = read_json(STATE_PATH)
    config = read_json(CONFIG_PATH)
    phase = args.phase or state.get("current_phase", "P06")
    enforce_lock(state, phase)
    result = {
        "phase": phase,
        "status": state.get("status"),
        "queue_index": state.get("phase_queue", []).index(phase) if phase in state.get("phase_queue", []) else -1,
        "forbidden_actions": config.get("forbidden_actions", []),
        "integrity_enabled": bool(config.get("integrity", {}).get("sha256_manifest")),
    }
    append_log("dry-run", state.get("status", "planning"), phase, "validation only")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="VVIP master orchestrator")
    sub = parser.add_subparsers(dest="cmd", required=True)

    status = sub.add_parser("status", help="show orchestrator status")
    status.set_defaults(func=cmd_status)

    integrity = sub.add_parser("integrity-check", help="verify checkpoint integrity")
    integrity.set_defaults(func=cmd_integrity_check)

    resume = sub.add_parser("resume", help="resume current locked phase")
    resume.add_argument("--phase", default="", help="phase id")
    resume.set_defaults(func=cmd_resume)

    emergency = sub.add_parser("emergency-stop", help="activate emergency stop")
    emergency.add_argument("--reason", required=True, help="documented reason")
    emergency.set_defaults(func=cmd_emergency_stop)

    dry_run = sub.add_parser("dry-run", help="validate without changing production")
    dry_run.add_argument("--phase", default="", help="phase id")
    dry_run.set_defaults(func=cmd_dry_run)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
