(function(root,factory){const dep=typeof module==='object'&&module.exports?require('./pr36-signature.js'):root.VVIP_PR36_SIGNATURE;const api=factory(dep);if(typeof module==='object'&&module.exports)module.exports=api;else root.VVIP_PR36_POLICY=api;})(typeof globalThis!=='undefined'?globalThis:this,function(signature){
  'use strict';
  const M=1024*1024;const CONSTANTS=Object.freeze({maxPhotos:7,maxFileBytes:15*M,maxTotalBytes:60*M,maxHeaderBytes:262144,maxPixels:40000000,minWidth:320,minHeight:240,maxWidth:1600,maxHeight:1200,webpQuality:.82,jpegQuality:.86,maxConcurrency:2,photoTimeoutMs:20000,sessionTimeoutMs:120000,debounceMs:250});
  const ALLOWED=Object.freeze(['image/jpeg','image/png','image/webp']);
  function createMediaError(code){const e=new Error(code);e.code=code;return e;}
  function validateSelection(files,existingCount){const list=Array.from(files||[]);if(list.length+(existingCount||0)>CONSTANTS.maxPhotos)throw createMediaError('too_many_photos');let total=0;for(const f of list){if(!f||!ALLOWED.includes(f.type))throw createMediaError('mime_not_allowed');if(!Number.isFinite(f.size)||f.size<1)throw createMediaError('unknown_format');if(f.size>CONSTANTS.maxFileBytes)throw createMediaError('source_too_large');total+=f.size;}if(total>CONSTANTS.maxTotalBytes)throw createMediaError('selection_total_too_large');return list;}
  async function validateSource(file,options){const o=options||{};if(o.signal&&o.signal.aborted)throw createMediaError('cancelled');if(!file||!ALLOWED.includes(file.type))throw createMediaError('mime_not_allowed');if(!Number.isFinite(file.size)||file.size<1)throw createMediaError('unknown_format');if(file.size>CONSTANTS.maxFileBytes)throw createMediaError('source_too_large');const limit=Math.min(file.size,CONSTANTS.maxHeaderBytes);const read=o.readHeader||(async f=>new Uint8Array(await f.slice(0,limit).arrayBuffer()));let bytes;try{bytes=await read(file,limit);bytes=bytes instanceof Uint8Array?bytes:Uint8Array.from(bytes||[]);if(bytes.length>limit)bytes=bytes.slice(0,limit);if(o.signal&&o.signal.aborted)throw createMediaError('cancelled');const detected=signature.detectSignature(bytes);if(!detected)throw createMediaError('unknown_format');if(detected!==file.type)throw createMediaError('signature_mismatch');const size=signature.dimensions(bytes,detected);if(!size||!Number.isInteger(size.width)||!Number.isInteger(size.height)||size.width<1||size.height<1)throw createMediaError('unknown_format');if(size.width<CONSTANTS.minWidth||size.height<CONSTANTS.minHeight)throw createMediaError('dimensions_too_small');if(size.width>Math.floor(CONSTANTS.maxPixels/size.height))throw createMediaError('decoded_pixels_exceeded');return{file,mimeType:detected,width:size.width,height:size.height};}catch(error){throw error&&typeof error.code==='string'?createMediaError(error.code):createMediaError('unknown_format');}finally{if(bytes)bytes.fill(0);}}
  function cleanAlt(v){return String(v==null?'':v).replace(/[<>\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,140);}
  function projectMetadata(items,coverId){const images=(Array.isArray(items)?items:[]).slice(0,7).map((x,i)=>{if(!x||typeof x.id!=='string'||!x.blob||!['image/jpeg','image/webp'].includes(x.blob.type)||!Number.isInteger(x.blob.size)||x.blob.size<1||x.blob.size>CONSTANTS.maxFileBytes||!Number.isInteger(x.width)||!Number.isInteger(x.height)||x.width<1||x.height<1||x.width>CONSTANTS.maxWidth||x.height>CONSTANTS.maxHeight||x.width*3!==x.height*4)throw createMediaError('encode_failed');return Object.freeze({imageId:cleanAlt(x.id).slice(0,80),position:i,altText:cleanAlt(x.altText),mimeType:x.blob.type,width:x.width,height:x.height,sizeBytes:x.blob.size});});return Object.freeze({images:Object.freeze(images),coverImageId:images.some(x=>x.imageId===coverId)?coverId:(images[0]?images[0].imageId:null)});}
  return Object.freeze({CONSTANTS,createMediaError,validateSelection,validateSource,projectMetadata});
});
